In [12]:
import numpy as np


In [13]:
## 1 dimensional array
my1dArray = np.array([1,2,3])
print(my1dArray)


[1 2 3]


In [14]:
## 2 dimensional array
my2dArray = np.array([[1,2,3], [4,5,6]])
print(my2dArray)


[[1 2 3]
 [4 5 6]]


In [15]:
my1dArray.dtype


dtype('int32')

In [16]:
my2dArray.dtype

dtype('int32')

In [21]:
## specifying the data type
my2dArrayfloat = np.array([[1,2,3], [4,5,6]], dtype='float32')
print(my2dArrayfloat)

[[1. 2. 3.]
 [4. 5. 6.]]


In [22]:
my2dArrayfloat.dtype

dtype('float32')

In [23]:
##combination of integer and a string
charArray1 = np.array([(1,'a',3),(4,5,'zzz')])



In [24]:
charArray1.dtype

dtype('<U11')

In [27]:
##array initialization

number_rows = 2
number_columns = 3

##array of zeros
array0s = np.zeros ((number_rows,number_columns), dtype=np.int32)



In [28]:
print(array0s)

[[0 0 0]
 [0 0 0]]


In [29]:
##array of ones
array1s = np.ones((number_rows,number_columns))
print(array1s)


[[1. 1. 1.]
 [1. 1. 1.]]


In [30]:
##array of fives
array5s =5* np.ones((number_rows,number_columns))
print(array5s)

[[5. 5. 5.]
 [5. 5. 5.]]


In [34]:
##array of sevens
array7s = np.full((number_rows,number_columns),7)
                
print(array7s)

[[7 7 7]
 [7 7 7]]


In [37]:
start =10
end = 27
step = 3
evenlystep = np.arange(start, end, step)
print(evenlystep)

[10 13 16 19 22 25]


In [38]:
## generating equally spaced number
number_samples =  4
evenlysample = np.linspace(start, end, number_samples)

In [39]:
print(evenlysample)

[10.         15.66666667 21.33333333 27.        ]


In [40]:
## identity matrix between 0 and 1
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [42]:
## generate floating numbers between 0 and 1 , 1 exclusive
random01 =np.random.random((2,3))
print(random01)

[[0.26997489 0.57693736 0.34468014]
 [0.84677535 0.78449605 0.97859117]]


In [47]:
## generate random.randint 
## print integer numbers specified, with last number not included
randomintRange = np.random.randint(0,10,(2,3))
print(randomintRange)

[[9 3 3]
 [5 2 3]]


In [48]:
## indexing inspection and slicing
a = np.array([[5,6,3], [2,5,1]])
print(a)
print('a has dimension: ', a.ndim)
print('a has shape: ', a.shape)
print('a has Size: ', a.size)
print('a has data type: ', a.dtype)



[[5 6 3]
 [2 5 1]]
a has dimension:  2
a has shape:  (2, 3)
a has Size:  6
a has data type:  int32


In [49]:
## indexing
a[1,2]


1

In [50]:
a[0:2, 1]


array([6, 5])

In [52]:
a[0,:2]


array([5, 6])

In [53]:
np.diag(a)

array([5, 5])

In [55]:
b = np.array([[5,6,3], [2,5,1],[4,4,4]])
print(b)

[[5 6 3]
 [2 5 1]
 [4 4 4]]


In [56]:
## the diagonal
np.diag(b)

array([5, 5, 4])

In [ ]:
## the diagonal flip



In [58]:
##Task 1
## taks odd numbers and replace with negative value

number_array = np.array([0,2,4,5,3,7,8,9,5,1])
print(number_array)

[0 2 4 5 3 7 8 9 5 1]


In [59]:
## write a function to calculate odd numbers

odd_number = np.where(number_array % 2 == 1)


In [60]:
## replace odd number with negative values 
number_array[odd_number] *= -1
print(number_array)

[ 0  2  4 -5 -3 -7  8 -9 -5 -1]
