In [12]:
import numpy as np


In [13]:
## 1 dimensional array
my1dArray = np.array([1,2,3])
print(my1dArray)


[1 2 3]


In [14]:
## 2 dimensional array
my2dArray = np.array([[1,2,3], [4,5,6]])
print(my2dArray)


[[1 2 3]
 [4 5 6]]


In [15]:
my1dArray.dtype


dtype('int32')

In [16]:
my2dArray.dtype

dtype('int32')

In [21]:
## specifying the data type
my2dArrayfloat = np.array([[1,2,3], [4,5,6]], dtype='float32')
print(my2dArrayfloat)

[[1. 2. 3.]
 [4. 5. 6.]]


In [22]:
my2dArrayfloat.dtype

dtype('float32')

In [23]:
##combination of integer and a string
charArray1 = np.array([(1,'a',3),(4,5,'zzz')])



In [24]:
charArray1.dtype

dtype('<U11')

In [27]:
##array initialization

number_rows = 2
number_columns = 3

##array of zeros
array0s = np.zeros ((number_rows,number_columns), dtype=np.int32)



In [28]:
print(array0s)

[[0 0 0]
 [0 0 0]]


In [29]:
##array of ones
array1s = np.ones((number_rows,number_columns))
print(array1s)


[[1. 1. 1.]
 [1. 1. 1.]]


In [30]:
##array of fives
array5s =5* np.ones((number_rows,number_columns))
print(array5s)

[[5. 5. 5.]
 [5. 5. 5.]]


In [34]:
##array of sevens
array7s = np.full((number_rows,number_columns),7)
                
print(array7s)

[[7 7 7]
 [7 7 7]]


In [37]:
start =10
end = 27
step = 3
evenlystep = np.arange(start, end, step)
print(evenlystep)

[10 13 16 19 22 25]


In [38]:
## generating equally spaced number
number_samples =  4
evenlysample = np.linspace(start, end, number_samples)

In [39]:
print(evenlysample)

[10.         15.66666667 21.33333333 27.        ]


In [40]:
## identity matrix between 0 and 1
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [42]:
## generate floating numbers between 0 and 1 , 1 exclusive
random01 =np.random.random((2,3))
print(random01)

[[0.26997489 0.57693736 0.34468014]
 [0.84677535 0.78449605 0.97859117]]


In [47]:
## generate random.randint 
## print integer numbers specified, with last number not included
randomintRange = np.random.randint(0,10,(2,3))
print(randomintRange)

[[9 3 3]
 [5 2 3]]


In [48]:
## indexing inspection and slicing
a = np.array([[5,6,3], [2,5,1]])
print(a)
print('a has dimension: ', a.ndim)
print('a has shape: ', a.shape)
print('a has Size: ', a.size)
print('a has data type: ', a.dtype)



[[5 6 3]
 [2 5 1]]
a has dimension:  2
a has shape:  (2, 3)
a has Size:  6
a has data type:  int32


In [49]:
## indexing
a[1,2]


1

In [50]:
a[0:2, 1]


array([6, 5])

In [52]:
a[0,:2]


array([5, 6])

In [53]:
np.diag(a)

array([5, 5])

In [55]:
b = np.array([[5,6,3], [2,5,1],[4,4,4]])
print(b)

[[5 6 3]
 [2 5 1]
 [4 4 4]]


In [56]:
## the diagonal
np.diag(b)

array([5, 5, 4])

In [ ]:
## the diagonal flip



In [58]:
##Task 1
## taks odd numbers and replace with negative value

number_array = np.array([0,2,4,5,3,7,8,9,5,1])
print(number_array)

[0 2 4 5 3 7 8 9 5 1]


In [59]:
## write a function to calculate odd numbers

odd_number = np.where(number_array % 2 == 1)


In [60]:
## replace odd number with negative values 
number_array[odd_number] *= -1
print(number_array)

[ 0  2  4 -5 -3 -7  8 -9 -5 -1]


In [63]:
## addition
a1 = np.array([[1,2,3],[7,1,3]])
a2 = np.array([[4,6,9], [2,5,1]])
add1 = a1 + a2
add2 = np.add(a1,a2)
print(add1)
print(add2)

[[ 5  8 12]
 [ 9  6  4]]
[[ 5  8 12]
 [ 9  6  4]]


In [67]:
## substract
sub1 = a1 - a2
sub2 = np.subtract(a1,a2)
print(sub1)
print(sub2)

[[-3 -4 -6]
 [ 5 -4  2]]
[[-3 -4 -6]
 [ 5 -4  2]]


In [68]:
## multiply
mul1 = a1 * a2
mul2 = np.multiply(a1,a2)
print(mul1)
print(mul2)


[[ 4 12 27]
 [14  5  3]]
[[ 4 12 27]
 [14  5  3]]


In [71]:
## divide

div1 = a1 / a2
div2 = np.divide(a1,a2)
print(div1)
print(div2)



[[0.25       0.33333333 0.33333333]
 [3.5        0.2        3.        ]]
[[0.25       0.33333333 0.33333333]
 [3.5        0.2        3.        ]]


In [74]:
a3 = np.array([[4,6], [2,5],[9,1]])
dotp = a1.dot(a3)
print(dotp)

[[35 19]
 [57 50]]


In [75]:
##other

exp = np.exp(a)
sqroot = np.sqrt(a)
sin = np.sin(a)
cos = np.cos(a)
log = np.log(a)

In [76]:
print(exp)

[[148.4131591  403.42879349  20.08553692]
 [  7.3890561  148.4131591    2.71828183]]


In [77]:
print(sqroot)

[[2.23606798 2.44948974 1.73205081]
 [1.41421356 2.23606798 1.        ]]


In [78]:
print(sin)

[[-0.95892427 -0.2794155   0.14112001]
 [ 0.90929743 -0.95892427  0.84147098]]


In [79]:
a5 = np.array([[1,2,5],[7,1,3]])
##  sum by column
sum1 = a5.sum(axis=1)
sum2 = np.sum(a5, axis=1)
print(sum1)



[ 8 11]


In [80]:
a5 = np.array([[1,2,5],[7,1,3]])
##  summation by row
sum1row = a5.sum(axis=0)
sum2row = np.sum(a5, axis=0)
print(sum1row)

[8 3 8]


In [81]:
## max

maxi = a5.max()
maxi2 = a5.max(axis=1)

print(maxi)
print(maxi2)

7
[5 7]


In [82]:
## standard deviation

stan_dev = np.std(a5)
print(stan_dev)

2.1921577396609844


In [85]:
## average
avg = np.mean(a5, axis=0)
avg2 = np.mean(a5)
print(avg)
print(avg2)

[4.  1.5 4. ]
3.1666666666666665


In [100]:
## Task 2 Triangle

A =np.array([0,0])
B = np.array([0,3])
C = np.array ([1,5,0])


In [157]:
from numpy import linalg as la

SyntaxError: invalid syntax (2408969025.py, line 1)

In [156]:
AB = la.norm(A-B)
AC = la.norm(A-C)
BC = la.norm(B -C)

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [154]:
AB = la.norm(A-B)
AC = la.norm(A-C)
BC = la.norm(B-C)

print(AB)
print(AC)
print(BC)


ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [107]:
## transpose
a7 =np.array([[1,2,5],[7,1,3]])
atr1 = np.transpose(a7)
atr2 = a7.T


In [108]:
print(a7)


[[1 2 5]
 [7 1 3]]


In [109]:
print(atr2)

[[1 7]
 [2 1]
 [5 3]]


In [110]:
## reshape

reshape1 = np.reshape(a7, (3,2))
print(reshape1)

[[1 2]
 [5 7]
 [1 3]]


In [113]:
a8 = np.array([[1,2,5],[7,1,3]])
a9 = np.array([[7,8],[4,1]])
a10 = np.array([[9],[9]])


In [116]:
abc = np.hstack([a8,a9,a10])
print(abc)

[[1 2 5 7 8 9]
 [7 1 3 4 1 9]]


In [118]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[7,8,9],[10,11,12]])
array3 = np.array([[13,14,15],[16,17,18]])

In [119]:
## stacking vertically

bac = np.vstack([array1,array2,array3])
print(bac)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [120]:
## concatenate

ab = np.concatenate((array1,array2,array3), axis = 1)
print(ab)

[[ 1  2  3  7  8  9 13 14 15]
 [ 4  5  6 10 11 12 16 17 18]]


In [121]:
ba = np.concatenate((array1,array2,array3), axis=0)
print(ba)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [125]:
# save a single array to a file
np.save('array_a ', array1)


In [126]:
np.savez('arrays_ab', arr1 = array1, arr2 = array2)

In [127]:
np.savetxt('array_a.txt', array1)

In [128]:
# delimiter

np.savetxt('array_a4.txt', array1, )


In [132]:
## delimiter
##%d = integer format
##%f === float number
##%s == string number
## %.2f --- float number to the nearest 2 decimal place
np.savetxt ('arrary_a4.txt', array1, delimiter=',', fmt='%.2f')

In [131]:
## save to csv file
np.savetxt('array.csv', array2, delimiter=',', fmt='%d')

In [138]:
# load from npy file

le = np.load('array_a .npy')
print(le)

[[1 2 3]
 [4 5 6]]


In [139]:
# load the text file

read_text = np.loadtxt('arrary_a4.txt', delimiter=',')
print(read_text)

[[1. 2. 3.]
 [4. 5. 6.]]


In [142]:
## export to .csv file

float_a = np.array([[1.99, 2.23],[5.30,7.75],[1.89,3.01]])
print(float_a)


[[1.99 2.23]
 [5.3  7.75]
 [1.89 3.01]]


In [149]:
## task done by me
import numpy as np

float_a = np.array([[1.99, 2.23], [5.30, 7.75], [1.89, 3.01]])
 ## round numbers 
rounded_array = np.round(float_a)

print(rounded_array)

[[2. 2.]
 [5. 8.]
 [2. 3.]]


In [152]:
## task with Abayomi

# create an array
float_a = np.array([[1.99, 2.23], [5.30, 7.75], [1.89, 3.01]])

# round number 

rounded_array =np.round(rounded_array, decimals=1)
print(rounded_array)

## add column header

column_header = ['col1','col2','col3']
## add row header

row_header = ['-----'], ['row1'],['row2'], ['row3']

## stacking rows and column header to the array
array_with_header = np.vstack([column_header,rounded_array])

final_array = np.hstack([row_header, array_with_header])


## save the array to csv file
np.savetxt('myfile.csv', final_array, delimiter=',', fmt='%s')


[[2. 2.]
 [5. 8.]
 [2. 3.]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2