In [52]:
import numpy as np 
import pandas as pd 
from sklearn.datasets import load_iris
from sklearn.preprocessing import MinMaxScaler, RobustScaler, StandardScaler, KBinsDiscretizer, LabelEncoder, OneHotEncoder
import matplotlib
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
%matplotlib inline
import re
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report
from sklearn.feature_selection import RFE
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from sklearn import svm



In [4]:
## read file
df = pd.read_excel('Practical_task_2.xlsx')
df

food_name           date_added        date_modified  \
0      succotash  2019-07-17 00:00:00  2019-10-16 00:00:00   
1         entree  2018-08-27 00:00:00  2019-12-24 00:00:00   
2         lychee  2018-12-24 00:00:00  2019-11-04 00:00:00   
3         cashew  2018-11-04 00:00:00  2019-01-23 00:00:00   
4         millet  2019-05-09 00:00:00  2019-06-04 00:00:00   
..           ...                  ...                  ...   
399        honey  2019-01-23 00:00:00  2019-04-21 00:00:00   
400        syrup                  NaN  2019-09-04 00:00:00   
401    milkshake  2019-12-19 00:00:00  2019-12-30 00:00:00   
402       celery  2019-08-25 00:00:00  2019-11-07 00:00:00   
403  dragonfruit  2019-05-18 00:00:00  2019-08-28 00:00:00   

    total_sales & online_sales  approved  
0                  2488 (1634)       1.0  
1                   2801 (496)       1.0  
2                   2706 (474)       1.0  
3                   788 (2535)       1.0  
4                  4931 (3637)       1.0  
..                         ...       ...  
399                3818 (2906)       1.0  
400                 808 (2502)       1.0  
401                1687 (4213)       1.0  
402                2293 (3371)       1.0  
403                3082 (1025)       1.0  

[404 rows x 5 columns]

In [5]:
## Data Cleaning
df.isnull().sum()

food_name                     1
date_added                    1
date_modified                 1
total_sales & online_sales    0
approved                      1
dtype: int64

In [6]:
## To identify rows in the DataFrame where at least one value is missing (NaN/null) across any column
df[df.isnull().any(axis = 1)]

food_name           date_added        date_modified  \
24   shish kebab  2019-08-08 00:00:00                  NaN   
70          rice  2018-03-23 00:00:00  2019-03-10 00:00:00   
192          NaN  2019-01-20 00:00:00  2019-09-03 00:00:00   
400        syrup                  NaN  2019-09-04 00:00:00   

    total_sales & online_sales  approved  
24                  4749 (568)       1.0  
70                       0 (0)       NaN  
192                2596 (2791)       1.0  
400                 808 (2502)       1.0

In [7]:
## to correct missing values REMOVING NULL VALUES
# Drop rows with missing values in Age, Embarked and Cabin columns
df = df.dropna(subset=['Age', 'Embarked', 'Cabin'])

KeyError: ['Age', 'Embarked', 'Cabin']

In [ ]:
import pandas as pd
import numpy as np

# Sample data
data = {
    'food_id': [24, 70, 192, 400],
    'food_name': ['shish kebab', 'rice', np.nan, 'syrup'],
    'date_added': ['2019-08-08 00:00:00', '2018-03-23 00:00:00', '2019-01-20 00:00:00', np.nan],
    'date_modified': [np.nan, '2019-03-10 00:00:00', '2019-09-03 00:00:00', '2019-09-04 00:00:00'],
    'total_sales & online_sales': ['NaN', '0 (0)', '2596 (2791)', '808 (2502)'],
    'approved': [1.0, np.nan, 1.0, 1.0]
}

# Create DataFrame
df = pd.DataFrame(data)

# 1. Correcting NaN values in 'food_name' column
df['food_name'] = df['food_name'].fillna('Unknown')

# 2. Correcting NaN values and converting date strings to datetime objects in 'date_added' and 'date_modified' columns
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')
df['date_modified'] = pd.to_datetime(df['date_modified'], errors='coerce')

# 3. Correcting 'total_sales & online_sales' column by splitting the values and converting them to integers
def process_sales(sales_str):
    if sales_str == 'NaN':
        return np.nan
    else:
        return int(sales_str.split()[0])

df['total_sales'] = df['total_sales & online_sales'].apply(process_sales)

# 4. Correcting 'approved' column by filling NaN values with 0
df['approved'] = df['approved'].fillna(0)

# Display the corrected DataFrame
print(df)


   food_id    food_name date_added date_modified total_sales & online_sales  \
0       24  shish kebab 2019-08-08           NaT                        NaN   
1       70         rice 2018-03-23    2019-03-10                      0 (0)   
2      192      Unknown 2019-01-20    2019-09-03                2596 (2791)   
3      400        syrup        NaT    2019-09-04                 808 (2502)   

   approved  total_sales  
0       1.0          NaN  
1       0.0          0.0  
2       1.0       2596.0  
3       1.0        808.0  


In [ ]:
df.head(50)

food_id    food_name date_added date_modified total_sales & online_sales  \
0       24  shish kebab 2019-08-08           NaT                        NaN   
1       70         rice 2018-03-23    2019-03-10                      0 (0)   
2      192      Unknown 2019-01-20    2019-09-03                2596 (2791)   
3      400        syrup        NaT    2019-09-04                 808 (2502)   

   approved  total_sales  
0       1.0          NaN  
1       0.0          0.0  
2       1.0       2596.0  
3       1.0        808.0

In [ ]:
## SCALE TO RANGE


In [ ]:
## load Iris dataset

iris  = load_iris()
X = iris.data

In [ ]:
Minimum = 2
Maximum  = 6

In [ ]:
## create an instance for my MinMaxScales
scaler = MinMaxScaler(feature_range=(Minimum, Maximum))
scaled_data = scaler.fit_transform(X)


In [ ]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [ ]:
scaled_data[:5]

array([[2.88888889, 4.5       , 2.27118644, 2.16666667],
       [2.66666667, 3.66666667, 2.27118644, 2.16666667],
       [2.44444444, 4.        , 2.20338983, 2.16666667],
       [2.33333333, 3.83333333, 2.33898305, 2.16666667],
       [2.77777778, 4.66666667, 2.27118644, 2.16666667]])

In [ ]:
## create an instance for RobotScaler
rob_scaler = RobustScaler()

## Fit and tranform the data
scaler_data = rob_scaler.fit_transform(X)


In [ ]:
scaler_data[:5]

array([[-0.53846154,  1.        , -0.84285714, -0.73333333],
       [-0.69230769,  0.        , -0.84285714, -0.73333333],
       [-0.84615385,  0.4       , -0.87142857, -0.73333333],
       [-0.92307692,  0.2       , -0.81428571, -0.73333333],
       [-0.61538462,  1.2       , -0.84285714, -0.73333333]])

In [ ]:
## Feature clipping
## set up a range to clip our features

min_clip = 0
max_clip = 2

## clip the features
clipped_features = np.clip(X,min_clip, max_clip)


In [ ]:
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [ ]:
clipped_features[:5]

array([[2. , 2. , 1.4, 0.2],
       [2. , 2. , 1.4, 0.2],
       [2. , 2. , 1.3, 0.2],
       [2. , 2. , 1.5, 0.2],
       [2. , 2. , 1.4, 0.2]])

In [ ]:
##LOGS Scaling

log_scaled = np.log(X)
log_scaled[:5]

array([[ 1.62924054,  1.25276297,  0.33647224, -1.60943791],
       [ 1.58923521,  1.09861229,  0.33647224, -1.60943791],
       [ 1.54756251,  1.16315081,  0.26236426, -1.60943791],
       [ 1.5260563 ,  1.13140211,  0.40546511, -1.60943791],
       [ 1.60943791,  1.28093385,  0.33647224, -1.60943791]])

In [ ]:
## Z score/standard scaler
std_scaler = StandardScaler()

## fit and transform the data
scaler_z = std_scaler.fit_transform(X)
scaler_z[:5]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])

In [ ]:
## BUCKETING
## load the data into dataframe
data = pd.DataFrame(iris.data, columns=iris.feature_names)

In [ ]:
## create buckets
number_buckets = 5

## initialize the instance of KBinsDiscretizer
dis = KBinsDiscretizer(n_bins=number_buckets, encode='ordinal', strategy='uniform')

## fit and transform the data
transfrom_dis = pd.DataFrame(dis.fit_transform(data), columns = data.columns)

transfrom_dis.head(5)



c:\Users\kater\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_discretization.py:248: FutureWarning: In version 1.5 onwards, subsample=200_000 will be used by default. Set subsample explicitly to silence this warning in the mean time. Set subsample=None to disable subsampling explicitly.
  warnings.warn(


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                1.0               3.0                0.0               0.0
1                0.0               2.0                0.0               0.0
2                0.0               2.0                0.0               0.0
3                0.0               2.0                0.0               0.0
4                0.0               3.0                0.0               0.0

In [ ]:
data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [ ]:
df = pd.read_csv('train_original.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Unnamed: 12 Unnamed: 13  
0        0         A/5 21171   7.2500   NaN        S        644.0           S  
1        0          PC 17599  71.2833   C85        C        168.0           C  
2        0  STON/O2. 3101282   7.9250   NaN        S         77.0           Q  
3        0            113803  53.1000  C123        S          NaN         NaN  
4        0            373450   8.0500   NaN        S          NaN         NaN  
..     ...               ...      ...   ...      ...          ...         ...  
886      0            211536  13.0000   NaN        S          NaN         NaN  
887      0            112053  30.0000   B42        S          NaN         NaN  
888      2        W./C. 6607  23.4500   NaN        S          NaN         NaN  
889      0            111369  30.0000  C148        C          NaN         NaN  
890      0            370376   7.7500   NaN        Q          NaN         NaN  

[891 rows x 14 columns]

In [ ]:
## Label encoder 
## declare an instance
le =LabelEncoder()
df['Sex_encoded'] = le.fit_transform(df['Sex'])
df.head(5)



PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Unnamed: 12 Unnamed: 13  \
0      0         A/5 21171   7.2500   NaN        S        644.0           S   
1      0          PC 17599  71.2833   C85        C        168.0           C   
2      0  STON/O2. 3101282   7.9250   NaN        S         77.0           Q   
3      0            113803  53.1000  C123        S          NaN         NaN   
4      0            373450   8.0500   NaN        S          NaN         NaN   

   Sex_encoded  
0            1  
1            0  
2            0  
3            0  
4            1

In [ ]:
## get dummies
new_sex = pd.get_dummies(df['Sex'])


In [ ]:
df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Unnamed: 12 Unnamed: 13  \
0      0         A/5 21171   7.2500   NaN        S        644.0           S   
1      0          PC 17599  71.2833   C85        C        168.0           C   
2      0  STON/O2. 3101282   7.9250   NaN        S         77.0           Q   
3      0            113803  53.1000  C123        S          NaN         NaN   
4      0            373450   8.0500   NaN        S          NaN         NaN   

   Sex_encoded  
0            1  
1            0  
2            0  
3            0  
4            1

In [ ]:
##concatenate

df = pd.concat([df,new_sex], axis=1)


In [ ]:
## drop the old columns of sex
df.drop(columns=['Sex'], inplace=True)

In [ ]:
df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0      1      0   
2                             Heikkinen, Miss. Laina  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0      1      0   
4                           Allen, Mr. William Henry  35.0      0      0   

             Ticket     Fare Cabin Embarked  Unnamed: 12 Unnamed: 13  \
0         A/5 21171   7.2500   NaN        S        644.0           S   
1          PC 17599  71.2833   C85        C        168.0           C   
2  STON/O2. 3101282   7.9250   NaN        S         77.0           Q   
3            113803  53.1000  C123        S          NaN         NaN   
4            373450   8.0500   NaN        S          NaN         NaN   

   Sex_encoded  female   male  
0            1   False   True  
1            0    True  False  
2            0    True  False  
3            0    True  False  
4            1   False   True

In [ ]:
## one hot encoder
one = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

## fit and transform
one_transform =one.fit_transform(df[['Embarked']])

## create dataframe from array that will be gebarated above
one_df = pd.DataFrame(one_transform, columns = one.get_feature_names_out(['Embarked']))

In [ ]:
## decomposting the data

new_data = pd.DataFrame({'datetime':['2024-01-01 10:30:00','2024-10-01 12:30:59' ]})

## convert this to date time
new_data['datetime']= pd.to_datetime(new_data['datetime'])

## split the date time

new_data['year']= new_data['datetime'].dt.year
new_data['month']= new_data['datetime'].dt.month
new_data['hour']= new_data['datetime'].dt.hour
new_data['day_name']= new_data['datetime'].dt.day_name()

new_data

datetime  year  month  hour day_name
0 2024-01-01 10:30:00  2024      1    10   Monday
1 2024-10-01 12:30:59  2024     10    12  Tuesday

In [ ]:
X= pd.DataFrame(iris.data,columns=iris.feature_names)

In [ ]:
## FEATURE SELECTION

corr_mat = X.corr().abs()

#created matrix of oneswith the same shape with corr mat
mask = np.triu(np.ones_like(corr_mat,dtype=bool))

In [ ]:
mask_df = corr_mat.mask(mask)
mask_df

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)                NaN               NaN                NaN   
sepal width (cm)            0.117570               NaN                NaN   
petal length (cm)           0.871754          0.428440                NaN   
petal width (cm)            0.817941          0.366126           0.962865   

                   petal width (cm)  
sepal length (cm)               NaN  
sepal width (cm)                NaN  
petal length (cm)               NaN  
petal width (cm)                NaN

In [ ]:
drop_it =[ c for c in mask_df.columns if any(mask_df[c]>0.95)]
drop_it

['petal length (cm)']

In [ ]:
reduced_df = X.drop(drop_it, axis=1)
reduced_df

sepal length (cm)  sepal width (cm)  petal width (cm)
0                  5.1               3.5               0.2
1                  4.9               3.0               0.2
2                  4.7               3.2               0.2
3                  4.6               3.1               0.2
4                  5.0               3.6               0.2
..                 ...               ...               ...
145                6.7               3.0               2.3
146                6.3               2.5               1.9
147                6.5               3.0               2.0
148                6.2               3.4               2.3
149                5.9               3.0               1.8

[150 rows x 3 columns]

In [ ]:
## PCA
pca =PCA(n_components=3)

X_pca = pca.fit_transform(X)

In [ ]:
X_pca[:5]

array([[-2.68412563,  0.31939725, -0.02791483],
       [-2.71414169, -0.17700123, -0.21046427],
       [-2.88899057, -0.14494943,  0.01790026],
       [-2.74534286, -0.31829898,  0.03155937],
       [-2.72871654,  0.32675451,  0.09007924]])

In [ ]:
## print the ratio
pca.explained_variance_ratio_

array([0.92461872, 0.05306648, 0.01710261])

KNN


In [8]:
## read data
data = pd.read_csv('fruit_types.csv')
data.head()

fruit_name fruit_subtype  mass  width  height  color_score
0      apple  granny_smith   192    8.4     7.3         0.55
1      apple  granny_smith   180    8.0     6.8         0.59
2      apple  granny_smith   176    7.4     7.2         0.60
3   mandarin      mandarin    86    6.2     4.7         0.80
4   mandarin      mandarin    84    6.0     4.6         0.79

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   fruit_name     59 non-null     object 
 1   fruit_subtype  59 non-null     object 
 2   mass           59 non-null     int64  
 3   width          59 non-null     float64
 4   height         59 non-null     float64
 5   color_score    59 non-null     float64
dtypes: float64(3), int64(1), object(2)
memory usage: 2.9+ KB


In [10]:
## missing values
data.isnull().sum()

fruit_name       0
fruit_subtype    0
mass             0
width            0
height           0
color_score      0
dtype: int64

In [11]:
## Label encoder
encoder = LabelEncoder()

## encode all variables in dataset
fruit_name_encoded = encoder.fit_transform(data.iloc[:,0])
fruit_subtype_encoded = encoder.fit_transform(data.iloc[:,1])
mass_encoded = encoder.fit_transform(data.iloc[:,2])
width_encoded = encoder.fit_transform(data.iloc[:,3])
height_encoded = encoder.fit_transform(data.iloc[:,4])
color_score_encoded = encoder.fit_transform(data.iloc[:,5])

In [15]:
##combine the encoded data
data = list(zip(fruit_name_encoded, fruit_subtype_encoded, mass_encoded, width_encoded,height_encoded, color_score_encoded))


In [16]:

##to put data into a dataframe
data = pd.DataFrame(data,columns=['fruit_name', 'fruit_subtype','mass','width','height','color_score'])
data.head()

fruit_name  fruit_subtype  mass  width  height  color_score
0           0              3    30     20       8            0
1           0              3    27     19       4            1
2           0              3    25     14       7            2
3           2              4     3      4       3           15
4           2              4     2      2       2           14

In [22]:
## split our data
data_to_use = data.iloc[:,1:6]
data_to_target = data.iloc[:,0]


In [23]:
X_train, X_test, y_train, y_test = train_test_split(data_to_use,data_to_target, test_size=0.3, random_state=32)

In [24]:
##buoild KNN model

knn_model =KNeighborsClassifier(n_neighbors=1)
knn_model.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [36]:
## make prediction
y_pred_knn = knn_model.predict(X_test)

In [37]:
print('Accuracy', metrics.accuracy_score(y_test,y_pred_knn))

Accuracy 0.9444444444444444


In [38]:
from math import sqrt

In [39]:
## root mean square error
print('RMSE', sqrt(metrics.mean_squared_error(y_test,y_pred_knn)))


RMSE 0.4714045207910317


DECISION TREE

In [46]:
##Gini
decision_gini =DecisionTreeClassifier()

##Max depth
decision_depth= DecisionTreeClassifier(max_depth=3)

## Entropy
decision_entropy =DecisionTreeClassifier(criterion='entropy')

In [47]:
## fit the trees
decision_gini.fit(X_train,y_train)

DecisionTreeClassifier()

In [48]:
decision_depth.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=3)

In [49]:
decision_entropy.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [50]:
y_pred_gini = decision_gini.predict(X_test)
y_pred_depth =decision_depth.predict(X_test)
y_pred_entropy= decision_entropy.predict(X_test)

In [51]:
print('Accuracy(gini):', metrics.accuracy_score(y_test,y_pred_gini))
print('Accuracy(depth):', metrics.accuracy_score(y_test,y_pred_depth))
print('Accuracy(entropy):', metrics.accuracy_score(y_test,y_pred_entropy))

Accuracy(gini): 0.8888888888888888
Accuracy(depth): 0.8888888888888888
Accuracy(entropy): 0.8888888888888888


SVM

In [53]:
## create an object for svm

clfLinear = svm.SVC(kernel='linear')
clfsigmoid = svm.SVC(kernel='sigmoid')
clfrbf = svm.SVC(kernel='rbf')

In [54]:
##train model
clfLinear.fit(X_train,y_train)
clfsigmoid.fit(X_train,y_train)
clfrbf.fit(X_train,y_train)

SVC()

In [56]:
##make predictions
y_pred_linear = clfLinear.predict(X_test)
y_pred_sigmoid = clfsigmoid.predict(X_test)
y_pred_rbf = clfrbf.predict(X_test)

In [57]:
##check the accuracy
print('Accuracy(linear):', metrics.accuracy_score(y_test,y_pred_linear))
print('Accuracy(sigmoid):', metrics.accuracy_score(y_test,y_pred_sigmoid))
print('Accuracy(rbf):', metrics.accuracy_score(y_test,y_pred_rbf))

Accuracy(linear): 1.0
Accuracy(sigmoid): 0.16666666666666666
Accuracy(rbf): 1.0
